apiVersion: mocks.microcks.io/v1alpha1
kind: APIExamples
metadata:
  name: Pizza Lifecycle Events
  version: 1.0.0
operations:
  'SUBSCRIBE pizza/lifecycle':
    contextualizedAccepted:
      eventMessage:
        payload: |-
          {
            "specversion": "1.0",
            "id": "{{ uuid() }}",
            "source": "https://pizza-pattern.hungovercoders.com/pizza-service",
            "type": "com.hungovercoders.pizza.accepted.v1",
            "time": "{{ now(yyyy-MM-dd'T'HH:mm:ss'Z') }}",
            "subject": "{{ response.body/pizzaId }}",
            "commandid": "{{ response.body/commandId }}",
            "datacontenttype": "application/json",
            "data": {
              "size": "{{ request.body/size }}",
              "crust": "{{ request.body/crust }}",
              "toppings": {{ request.body/toppings }}
            }
          }
